src/index.tsx, src/styles/global-styles.tsx, src/styles/styled.d.tsx, src/styles/theme.tsx
1. 글로벌 스타일 파일 따로 만들었습니다. styled-reset에 빠져있는데 없으면 불편한 속성들도 몇개 있어서 아예 파일을 따로 만들어서 추가했습니다. 지금 글씨체도 설정되어있는데 추후 수정해야 합니다.
2. theme.tsx 만들었습니다. 지금 들어가있는 속성들은 임시 속성으로 예시를 위해 넣어놨습니다.
추후 디자인확정되면 변경해야합니다.
3. index.tsx에 themeprovider를 추가해 theme.tsx를 사용할 수 있도록 설정했습니다.
<br/>
+) 확인요청
theme.tsx에서 사용예제 보시고 원하시는 통일방법이 따로 있으시면 리뷰로 달아주세요
=> Docs: global-styles, theme 관련 파일 추가

public/index.html, src/Modal.tsx
index.html div id=portal 추가
ReactNode를 children으로 받는 Modal.tsx 작성
=> Feat: Modal 공용 컴포넌트 작성 #24

src/assets/icons/checkboxOff.svg, src/assets/icons/checkboxOn.svg, src/components/LoginSignUp.style.tsx, src/pages/Login.tsx
- 로그인/회원가입 공통 컴포넌트 사용해서 ui 완성
- 공통 컴포넌트 버튼 부분 css 수정(hover하면 커서 변경, 비활성화되면 hover해도 커서 변경x)
+++ 로그인 기능은 미완입니다 UI까지 작업했습니다
+++ theme 컬러 dev에 push되면 다시 수정하겠습니다
=> Feat: 로그인 와이어프레임 UI 완성 #3

src/utils/apiInstance.tsx
- api instance 파일에서 발생하는 axios config 타입 에러 수정했습니다.
=> !HOTFIX: axios header 타입 에러 수정

public/data/logOut.json, src/hooks/useLogOut.tsx
1. 로그아웃 로직을 커스텀 훅으로 분리했습니다.
2. 분리한 커스텀 훅 안에 로그아웃 함수를 작성하고, 로그아웃 api 까지 작성했습니다.
로그아웃 커스텀 훅 사용 예시입니다
다른 방법이 있다면 편하신대로 사용하셔도 됩니다~
```
//Nav.tsx
const Nav = () => {
const logOut = useLogOut();
const clickLogOutBtn = async () => {
await logOut();
}
return(
<button onClick={clickLogOutBtn}>로그아웃</button>
)
}
```
=> Feat: 로그아웃 커스텀 훅 완성 #62

.eslintrc.json
설정을 잘못 입력한 부분이 있어 추가로 수정하였습니다.
=> Docs: .eslintrc 추가 수정

src/components/atom/CheckLabel.tsx
1. 체크박스 + 라벨이 표시되는 컴포넌트 입니다.
2. 필수로 넘겨줘야 하는 props는 2가지 입니다.
-1. label(string): 로그인 상태 유지, 연령 무관, 성별 무관 등 라벨
-2. onClick(()=>void): 체크박스가 클릭될 때 실행되는 함수
3. 피그마 상 default, focus, active, hover 모두 구현되어있습니다. (focus는 :focus-visible을 사용해서 tab으로 포커싱이 이루어질 때만 적용됩니다)
혹시 적용해서 작업하시다가 수정되어야 할 부분이 있거나 optional로 추가되어야 할 props가 있다면 알려주세요!
=> Feat: CheckLabel 컴포넌트 완성

src/App.tsx, src/index.tsx
- index.tsx에 query provider를 추가했습니다.
- app.tsx에 react-query devtool을 추가했습니다.
- 화면 좌측 하단에 귀여운 아이콘이 하나 생성되어 있습니다. 크게 신경쓰지 않으셔도 됩니다.
=> Feat: react-query 추가

src/apis/login.tsx, src/apis/signUp.tsx, src/pages/Login.tsx, src/utils/apiInstance.tsx
1. 토큰 있는상태로 로그인페이지 접속시 메인페이지로 리다이렉트
2. 로그인요청로직, 로그인 성공 후 로컬스토리지에 정보저장하는 로직 분리
=> Fix: 토큰 있는 상태로 로그인페이지접속시 리다이렉트, 로그인 로직 수정 #95

src/components/atom/Searchbar.tsx, src/components/onelineReview/OnelineWrite.tsx, src/pages/Main.tsx
- width 값을 props로 받습니다.
- placeholder 를 props로 넘기면 글자가 표시됩니다.
=> Feat: searchbar 컴포넌트 작성했습니다.

src/assets/icons/plusLarge.svg, src/components/Editor.tsx, src/pages/BlogReviewWrite.tsx
- 컴파운드 컴포넌트화 완료했습니다.
- Editor.TextInputArea 컴포넌트에 textChangeHandler 함수를 패스해주시면 됩니다. 
- 보다 자세한 사용법은 디스코드에 스크린샷과 함께 첨부하겠습니다.
=> Feat: 에디터 컴파운드 컴포넌트화 완료 

src/components/Editor.tsx, src/pages/BlogReviewWrite.tsx
동규님 확인부탁드립니다!
name: 하나의 핸들러 함수에서 입력값을 관리하기 위함
value: 수정페이지인 경우, 기존의 입력값을 처음에 보여주기 위함
=> Fix: 에디터 컴포넌트 name, value props 추가

src/components/Calendar.tsx, src/pages/BlogReviewWrite.tsx
!! 적용하고 나면  Mate.tsx 컴포넌트에 에러가 발생합니다. 작업 중일 것이라고 생각해서 충돌날까봐 수정하지 않고 두었습니다. 
- const [selectedDate, setSelectedDate] = useState("") 중 setSelectedDate를 props로 받습니다.
- 날짜를 선택하면 selectedDate에 "YYYY-MM-DD"형태의 문자열을 저장합니다.
=> Feat: 캘린더 컴포넌트 수정

src/components/Calendar.tsx
=> Fix: 캘린더 컴포넌트 수정

src/apis/oneLineReviewApis.tsx, src/components/ReviewWrapper.tsx, src/components/onelineReview/OnelineCard.tsx, src/components/onelineReview/OnelineWrite.tsx, src/pages/OnelineWrapper.tsx
=> Hotfix: import 경로오류 수정

src/Modal.tsx, src/components/onelineReview/OnelineCard.tsx
=> Fix: 모달 컴포넌트 props 수정

src/pages/ExhibitionList.tsx
=> Fix: ExhibitionList 공백 수정

src/apis/oneLineReviewApis.tsx, src/components/ReviewSearchbar.tsx, src/components/ReviewWrapper.tsx, src/components/onelineReview/OnelineCard.tsx, src/pages/OnelineWrapper.tsx
- 테스트를 용이하게 하기 위해 validation check는 일시적으로 주석 처리해뒀습니다.
- 마찬가지로 비동기 통신이 loading, error 상태일 때의 표기도 단순화한 상태입니다.
- 상기 2점은 다른 분들의 테스트가 문제 없이 통과되는 대로 수정해두겠습니다.
=> Feat: 한줄 리뷰 CRUD 기능 병합

src/components/ExhibitionChoice.tsx, src/components/HamburgerMenu.tsx, src/components/blogreview/ExhibitionSelect.tsx, src/components/blogreview/container/BlogReviewDetailContainer.tsx, src/components/blogreview/container/BlogReviewList.tsx, src/components/blogreview/presentation/BlogReviewCard.tsx, src/components/blogreview/presentation/BlogReviewDetailPresentation.tsx, src/pages/BlogReviewDetail.tsx, src/pages/BlogReviewModify.tsx, src/pages/BlogReviewWrite.tsx, src/utils/apimultipartInstance.tsx
- 전시회 선택 컴포넌트 전시회가 표시되지 않는 문제 픽스
- 선택된 전시회 정보 표시 및 x 버튼 구현
- 블로그 리뷰 상세정보 표시 && 현재 imageUrl이 null 값으로 들어가 있어 일시적으로 주석 처리함 
- 블로그 리뷰 작성 오류가 있어 백엔드와 테스트하며 조율중
=> Fix: 전시회 선택 컴포넌트 비표시 버그 수정

src/apis/blogReviewApis.tsx, src/apis/oneLineReviewApis.tsx, src/components/ExhibitionChoice.tsx, src/components/blogreview/container/BlogReviewDetailContainer.tsx, src/components/blogreview/container/BlogReviewList.tsx, src/components/blogreview/presentation/BlogReviewCard.tsx, src/pages/BlogReview.tsx, src/pages/BlogReviewDetail.tsx, src/pages/BlogReviewModify.tsx, src/pages/BlogReviewWrite.tsx, src/utils/apimultipartInstance.tsx
- 블로그 리뷰 작성에 이미지 있으면 버그 나는 것 수정했습니다.
- 병행하여 기존 axios 인스턴스로 대체중입니다. 완전히 제거하고 나면 multipart 인스턴스는 삭제하겠습니다. 
- Css가 깨진 부분 있는데 기능 테스트 완료하고 작업하겠습니다
=> Fix: 블로그리뷰 작성 이미지 업로드 메서드 수정

src/apis/oneLineReviewApis.tsx, src/components/blogreview/container/BlogReviewReadContainer.tsx, src/components/onelineReview/container/OneLineReadContainer.tsx, src/components/onelineReview/presentation/OnelineCard.tsx, src/components/onelineReview/presentation/OnelineWrite.tsx, src/types/oneLineReview.d.ts
=> Fix: 한줄 리뷰 수정기능 http 메서드 수정

src/pages/BlogReviewModify.tsx, src/pages/BlogReviewWrite.tsx, src/types/blogReview.d.ts
- 블로그 리뷰 수정시 유저가 삭제할 이미지를 선택하면 UI에도 반영되도록 수정했습니다.
- 블로그 리뷰 작성시 성공시 블로그 리뷰 리스트 페이지로 이동하도록 변경했습니다.
=> Feat: BlogReviewModify 컴포넌트 이미지 삭제 시 UI에 반영되도록 수정

src/components/Editor.tsx, src/pages/MateWrite.tsx
1. placeholder추가
2. TextArea에 hover시 테두리 및 그림자 추가 (피그마에 새로 추가됨)
4. padding: 20px 추가
5. 에디터 컨테이너에 max-width 1200삭제 -> 에디터에 max width를 붙이는게 아니라 사영하는 페이지에 max-width를 붙여야 하는것 같아서 에디터컨테이너에 max-width 삭제하고 메이트 작성페이지에 max-width 1200추가했습니다
6. 공통 에디터 컴포넌트 TextArea 높이 300px 고정
+) 주석쳐둔 이유는 동규님 컴포넌트기 때문에 동규님이 확인해주시면 주석삭제하고 머지하기 위해서입니다!
=> Design: 메이트 작성글 넓이, 블로그/메이트 작성글 공용 Editor 컴포넌트 css 수정

src/apis/logOut.tsx, src/apis/useRefreshToken.tsx
토큰 만료 응답 시 로그아웃 버튼을 클릭하면 한번 클릭 후 다시 클릭해야 하는 버그가 있어 수정했습니다.
=> Fix: 토큰만료시에도 로그아웃 버튼 누르면 바로 로그아웃 되도록 수정

src/pages/MateList.tsx
=> Design: 메이트글 목록 max-width 추가

src/apis/member.tsx, src/components/atom/SimpleInput.tsx, src/components/mypage/WrittenBlogReview.tsx, src/components/mypage/WrittenSimpleReview.tsx, src/components/onelineReview/container/OnelineModifyContainer.tsx, src/components/onelineReview/presentation/MypageOnelineCard.tsx, src/components/onelineReview/presentation/OnelineCard.tsx, src/components/onelineReview/presentation/OnelineModify.tsx, src/components/onelineReview/presentation/OnelineWrite.tsx, src/pages/BlogReview.tsx, src/types/blogReview.d.ts, src/types/modifyPlaceholder.d.ts, src/types/oneLineReview.d.ts
- 한줄리뷰의 수정/ 삭제에 작성 회원이 맞는지 확인하는 로직을 추가했습니다.
- 한줄리뷰 수정시 이제 기존에 작성한 내용을 확인할 수 있습니다.
- 지난 pr리뷰 반영사항은 커밋 히스토리가 꼬여 이 브랜치에 반영했습니다.
=> Feat: 한줄리뷰 수정 기능 강화

src/components/blogreview/presentation/BlogReviewDetailPresentation.tsx
- 슬라이더 표시 수정및 목데이터용 배경색 삭제
- 사용자 프로필 이미지 반영
=> Fix: 블로그 상세페이지 수정

src/components/atom/Selectbox.tsx
=> Design: 셀렉트박스 그림자 추가

src/components/HamburgerMenu.tsx
머지과정에서 hamburgerMenu 파일의 코드 오류가 발생하여 이를 수정했습니다.
=> !HOTFIX: 머지 과정에서 생긴 코드 오류 수정

src/pages/BlogReviewWrite.tsx
=> Fix: 블로그리뷰 빈칸 작성시 다른 페이지로 이동하는 버그 수정

src/apis/member.tsx, src/components/blogReviewList/ReviewCardList.tsx, src/components/mypage/BookMarkedBlog.tsx, src/components/mypage/WrittenBlogReview.tsx
=> Feat: 마이페이지 북마크한 블로그리뷰 조회기능 작성

src/components/blogreview/container/BlogReviewReadContainer.tsx, src/components/reviewCommon/ReviewWrapper.tsx
=> Fix: 전시회 상세페이지에서 블로그리뷰 css 수정(재pr)

src/apis/member.tsx, src/components/mypage/MenuBtns.tsx, src/components/mypage/container/LikedBlogReviewContainer.tsx, src/pages/Mypage.tsx
=> Feat: 마이페이지 좋아요한 블로그리뷰 리스트 조회기능 작성

src/components/blogreview/presentation/BlogReviewPresentation.tsx, src/components/mypage/BookMarkedBlog.tsx, src/components/mypage/container/LikedBlogReviewContainer.tsx, src/components/onelineReview/presentation/OnelineWrite.tsx, src/components/signUp/CommonOnly.tsx
한꺼번에 처리하면 추적이 힘들다고 하셔서 잘라올립니다. 변경사항은
1. 블로그리뷰 상세페이지 이미지 없을경우 DOM에서 슬라이더 삭제
2. 회원가입, 한줄리뷰 표시 연도 최신순으로 변경
3. ...isloading JSX 삭제
=> Feat: 피드백 반영

src/components/mate/CommentList.tsx, src/components/mate/MateTop.tsx, src/pages/Mate.tsx
- 메이트글 상세페이지가 화면넓이에 따라 여백이 달라지도록 변경되었습니다.
- 반응형추가되어 레이아웃이 깨지지 않습니다(혹시 깨지는 부분 발견하면 알려주세요!)
=> Design: 메이트글 상세페이지 반응형 추가

src/components/onelineReview/presentation/MypageOnelineCard.tsx, src/components/onelineReview/presentation/OnelineCard.tsx
- 한줄 리뷰 카드의 별점표시 함수를 교체했습니다.
리팩토링은 한 브랜치에서 진행하는게 나을까요?
=> Refactor/rate: 한줄리뷰 별점 표시 함수를 교체했습니다.

src/components/blogreview/container/BlogReviewTop.tsx
- 블로그리뷰 삭제버튼 클릭시 모달을 띄우고 메세지를 교체했습니다.
=> Refactor: 블로그리뷰 삭제 모달 교체

src/components/onelineReview/container/OneLineReadContainer.tsx
=> Fix/simplenolist : 전시회 상세페이지 한줄리뷰 nolist 컴포넌트 추가

src/App.tsx, src/components/blogreview/ExhibitionSelect.tsx, src/components/blogreview/container/BlogReviewReadContainer.tsx, src/components/onelineReview/container/OneLineReadContainer.tsx, src/components/onelineReview/container/OnelineModifyContainer.tsx, src/components/onelineReview/container/OnelineWriteContainer.tsx, src/components/onelineReview/presentation/OnelineCard.tsx, src/components/onelineReview/presentation/OnelineModify.tsx, src/components/onelineReview/presentation/OnelineWrite.tsx, src/components/reviewCommon/ReviewSearchBar.tsx, src/pages/BlogReviewWrite.tsx
- 블로그 / 한줄리뷰 정렬 순서 강조표시 수정
- 블로그 리뷰 작성시 빈칸 alert 표시 안되는 버그 수정
- 한줄리뷰 별점 가로로 표시되도록 수정
- 한줄리뷰 작성시 글자수 표시, 안내 alert
- 한줄리뷰 작성시 초기값 적용, 작성 길이에 따라 등록하기 버튼 비활성화
- 블로그리뷰 페이지네이션 정렬
- 검색창 비활성화 
- 리액트 쿼리 데브툴 제거
=> Fix: 피드백 반영

src/pages/Login.tsx
이메일/비밀번호 찾기 기능 추가예정이 없으므로 삭제했습니다
=> Delete: 로그인페이지 이메일/비밀번호 찾기 기능 삭제

src/apis/blogdetailbookMarkApis.tsx, src/apis/bloglikeApis.tsx, src/apis/exhibition.tsx, src/apis/member.tsx, src/components/blogreview/presentation/BlogReviewPresentation.tsx
마이페이지
- 북마크 추가한 블로그글 /api/blogs/bookmarks/me?page={pageNo} 으로 변경
- 북마크 추가한 전시글 /api/exhibitions/bookmarks/me?page={pageNo} 으로 변경
- 북마크 추가한 메이트글 /api/mates/bookmarks/me?page={pageNo} 으로 변경
북마크 추가 / 삭제
- 블로그글 /api/blogs/bookmarks/{blogId} 으로 변경(put)
- 전시글  /api/exhibitions/bookmarks/{exhibitionId} 으로 변경
- 추가/ 삭제여부 알림창 추가
좋아요 추가 / 삭제
- 블로그글 /api/blogs/likes/{blogId} 으로 변경(put)
- 추가/ 삭제여부 알림창 추가
=> Fix: 변경된 api 주소로 변경

src/components/onelineReview/container/OneLineReadContainer.tsx, src/components/onelineReview/presentation/OnelineCard.tsx, src/components/reviewCommon/ReviewSearchBar.tsx
- 한 줄 리뷰간 간격 재조정했습니다.
- 한 줄 리뷰 내부 폰트 크기 상승, 간격조절
- 서치바 컴포넌트 클릭시 볼드체 및 컬러 유지하도록 수정했습니다.
=> Fix: 한 줄 리뷰 서치바 필터영역 css 수정 

src/components/ExhibitionChoice.tsx, src/components/blogreview/ExhibitionSelect.tsx, src/components/exhbChoiceModal/ExhbCardListModal.tsx
- 전시회 모달 세로 스크롤화 했습니다.
- 그리드와 미디어 쿼리로 약간의 반응형 디자인을 첨가했습니다.
- 페이지네이션을 추가했습니다.
=> Feat: 전시회 모달 스크롤화

src/pages/BlogReviewModify.tsx, src/pages/BlogReviewWrite.tsx
- date-fns 라이브러리 형식에 맞게 작성하지 않아서 나던 오류를 수정했습니다.
=> Fix: 블로그리뷰 작성페이지 selectedDate 초기값 포맷형태 yyyy-MM-dd로 수정

src/components/Calendar.tsx, src/components/Editor.tsx, src/components/blogreview/ReviewTitle.tsx, src/components/blogreview/presentation/BlogReviewPresentation.tsx, src/pages/BlogReview.tsx, src/pages/BlogReviewModify.tsx, src/pages/BlogReviewWrite.tsx
- 블로그 리뷰 수정 컴포넌트 기존 글 정보 표시되도록 수정했습니다.
- 블로그 리뷰 작성/ 수정  취소하기 버튼에 네비게이션 추가했습니다.
- 캘린더 컴포넌트 수정했습니다.
=> Fix: 블로그 리뷰 수정글 기존 글 정보 표시되도록 수정

src/components/blogreview/container/BlogReviewReadContainer.tsx, src/components/blogreview/presentation/BlogReviewPresentation.tsx, src/pages/BlogReview.tsx, src/pages/BlogReviewWrite.tsx
- 블로그리뷰 본문 line-height 조절, 개행문자 반영처리
- 좋아요버튼 클릭시 메세지 수정
- 북마크버튼 클릭시 메세지 수정
- 페이지네이션 표시 오류 수정
로컬 테스트는 마쳤습니다
=> Fix: 블로그 리뷰 본문, 좋아요/북마크 메세지 수정

src/pages/BlogReview.tsx
- 블로그 리뷰 상세 페이지에서 이전의  블로그 id 정보가 표시되는 문제 해결
=> Fix: 리뷰 상세페이지 state 갱신 지연 수정

src/apis/exhbList.tsx, src/components/ExhibitionChoice.tsx, src/components/exhibitionList/Filters.tsx, src/pages/ExhibitionList.tsx, src/pages/MateList.tsx, src/types/mateList.d.ts
#475 병합입니다.
메인브랜치에는 핫픽스로 머지 완료되었습니다. dev만 확인부탁드립니다.
=> HOTFIX: 전시글 목록조회, 메이트글 목록조회 api 응답형식 미반영으로 인한 에러 수정

README.md
- vscode에서 수정 후 올리려고 하니 마크다운 양식이 깨져서 여기서 올립니다:)
=> ReadMe: 백엔드 기술스택 이미지 변경

src/hooks/useDebounce.tsx, src/pages/BlogReviewList.tsx
- useDebounce 훅 추가
- 엔드포인트가 달라 검색시 기존 데이터와 분기하여 표시
! 옆에 리뷰등록 버튼때문에 엔터로 제출하는 방식이 잘 안먹혀서 키보드 입력 있으면 일정 시간 후에 요청 보내는 방식으로 구현했어요
=> Feat: 블로그 리뷰 검색기능 작성

src/apis/member.tsx, src/components/exhibition/ExhbMateList.tsx, src/components/mypage/BookMarkedExhb.tsx, src/components/mypage/BookMarkedMate.tsx, src/components/mypage/WrittenMate.tsx
page info api가 수정되어 에러가 나는 페이지들을 전부 수정했습니다.
=> Fix: page info api 수정

src/components/exhibitionList/Filters.tsx
- 검색기능 리셋된 부분 새로운 SearchInput 컴포넌트에 맞게 수정해서 복원했습니다.
- 초기화 버튼을 추가해 검색어를 초기화할 수 있도록 하였습니다. (검색 후 검색어를 지우고 검색해도 초기화됩니다)
=> Fix: 전시회 목록 검색기능 리셋된 것 복원, 초기화버튼 추가

src/apis/mate.tsx, src/components/mate/MateListFilter.tsx, src/pages/MateList.tsx, src/types/mateList.d.ts
- 메이트글 제목으로 검색이 가능해졌습니다
- 초기화 버튼을 누르면 검색이 초기화됩니다
=> Feat: 메이트글 목록 제목 검색기능 추가
