myalley-project/myalley-fe

.eslintrc.json

- 스타일드 컴포넌트를 컴포넌트 리턴문 아래에 선언해 가독성을 올리기 위해
eslint no-use-before-define 설정 off로 변경했습니다.

Setting: eslint no-use-before-define 설정 off

---

src/styles/global-styles.tsx

와이어프레임 중 거의 모든 div, input, button의 border-radius가 30px인 것을 알았습니다.
일일히 설정하지 않고 global-style에서 설정한 후, border-radius가 30px이 아닌 것에만 따로 설정을 하는 것을 어떨까 하여 건의합니다!
@gandy818 @caffesale 의견 부탁드립니다~!

Design: global-style에 div, input, button border-radius 설정추가

---

package.json

저희 프로젝트에 js, jsx파일이 없는데 검사를 실행하려고 하니 오류가 나서 eslint 검사의 대상 파일 확장자 중 js, jsx를 삭제했습니다.

Setting: package.json eslint 대상 경로 변경

---

.gitignore
src/utils/apiInstance.tsx

api instance 생성해서 pr 날립니다! 조금 더 구체적인 설명은 아래 comment에 달았습니다.
궁금하거나 수정할만한 부분 있으면 피드백 부탁드립니다!
dev와 main에 오류 해결되고 두분 다 확인해주시면 머지하겠습니다.
1. api instance 생성: src > utils 폴더에 생성했습니다.
2. 요청 보내기 전 헤더에 토큰 첨부: 일일이 토큰을 넣어서 요청할 필요가 없습니다.
3. instance의 baseURL은 보안을 위해 .env 파일에서 관리:  깃허브에 올라가지 않기 때문에 각자 추가해야합니다.
api instance 사용예시도 같이 첨부해드립니다:)
```
//로그인 api (POST)
const clickSignUpBtn = async () => {
const reqBody = {~~~~요청 시 body에 첨부해서 보내는 데이터};
interface Response {~~~~요청 후 응답으로 받는 데이터의 타입}
try {
const res: AxiosResponse<Response> =
await apiInstance.post("/signup", reqBody);     // api 인스턴스 사용 , 첫번째 인자로 "/내가 보낼 url",
두번째 인자로 request body(보내야 한다면)
~~~~
요청 성공 시 처리할 로직
~~~~
} catch (err) {
~~~
요청 실패 시 처리할 로직
~~~
}
};
```

Feat: api instance 생성, gitingnore에 .env파일 추가

---

.eslintrc.json

이벤트 버블링을 사용하는데 방해가 되어 문서에 명시된대로 off 했습니다.

Setting: jsx-a11y/no-static-element-interactions 무효화

---

src/components/PageNoBar.tsx
src/components/Pagination.tsx
src/components/exhibitionList/Filters.tsx
src/pages/ExhibitionList.tsx
src/types/exhbList.d.ts

1. 페이지네이션 컴포넌트 완성했습니다. pages, setPages, totalPage 세가지 props를 받습니다.
-1. pages: 시작페이지, 선택된 페이지의 정보를 담고있는 state입니다. { started: number, selected: number }
-2. setPages: pages의 set함수입니다.
-3. totalPage: api를 통해 얻는 총 페이지 수입니다. 부모 컴포넌트에서 state로 상태관리되고있는 값입니다. 
각자 작성하신 코드에 맞게 적용하시면 됩니다
제 코드 중 ExhibitionList.tsx(전시회 목록) 참고하시면 도움될 것 같습니다!
2. 컴포넌트 파일내에서 사용하는 아이콘 변수명 컨벤션대로 변경했습니다(arrowLeftIcon -> arrowLeft 등)
3. 화살표 클릭함수 분리: 전전, 이전, 다음, 다다음 화살표 클릭 이벤트를 핸들링하는 함수가 하나였는데, 보기 복잡해서 각각의 버튼을 핸들링하는 함수로 리팩토링했습니다.
4. PageNoBar에서 Pagination으로 파일명, 컴포넌트명 변경이 이루어져서 ExhibitionList컴포넌트에도 변경사항 적용했습니다.
5. 페이지 넘버 버튼, 좌우 화살표 버튼 active, hover, focus, default 디자인 다 적용되어있습니다.

Feat: 페이지네이션 컴포넌트 재사용하도록 수정

---

src/assets/icons/checkOff.svg
src/assets/icons/checkOn.svg
src/components/atom/CheckLabel.tsx

제가 컴포넌트만 완성하고 checkOn이랑 checkOff svg를 수정을 안해놔서
현재 메인에 CheckLabel 컴포넌트는 색이 반영이 안되네요 😥
수정사항 반영해서 pr합니다
이 pr이 머지되고 나면
svg에 props로 넘겨줘야 하는 색은 current로 되어있어서 그냥 img로 사용하신 분들은
색이 안나오게 되는게 정상입니다!
(이 아이콘은 전부 체크박스+라벨로 구성되어 있는 걸로 알아서
기존의 체크박스+라벨을 구성하신 분이 있다면
이 컴포넌트 사용하시면 됩니다!)
이런식으로 svg파일에 필요한 props 주석처리 해뒀습니다!

Design: checkOn, checkOff svg 색상 수정

---

src/apis/logOut.tsx
src/apis/member.tsx
src/components/HamburgerMenu.tsx
src/pages/Login.tsx

1. 로그아웃 시 삭제되는 정보 추가(사용자 아이디, 이메일, 프로필, 닉네임(이름), 회원권한)
2. 로그아웃 테스트하며 내정보조회 api 응답 키이름 수정(api문서에 맞게)
3. 햄버거메뉴에 로그아웃 로직 반영(로그아웃 버튼 클릭 시 로그아웃 api 호출)
4. 로그인 시 로컬스토리지에 저장되는 정보고 키이름 수정(api문서에 맞게)

Fix: 로그아웃 시 로컬스토리지 정보 삭제, 로그인 시 로컬스토리지 저장되는 정보 수정, 로그아웃버튼에 로그아웃 적용 #129

---

src/apis/logOut.tsx
src/apis/useRefreshToken.tsx
src/utils/removeLocalStorageItem.tsx

api 로직 변경요청이 들어와서 그에맞게 수정했습니다.
1. 로그아웃 할 때도 ACCESS토큰 만료 응답 받을 수 있고, 해당 응답 받을 시 리프레시 토큰 인증api 호출하도록 api 수정
2. 로컬스토리지에서 회원정보, 토큰을 다 삭제하는 함수 생성. 유지보수를 위해 하나의 함수를 생성 후 필요한 파일에서 호출하여 사용했습니다.

Fix: 로그아웃, 리프레시 토큰 인증 api 수정

---

src/apis/getExhbList.tsx
src/apis/mate.tsx
src/components/NoList.tsx
src/components/exhibition/ExhbMateList.tsx
src/components/exhibitionList/ExhbCardList.tsx
src/components/exhibitionList/Filters.tsx
src/components/main/MainArticle.tsx
src/components/mate/MateCard.tsx
src/components/mypage/BookMarkedExhb.tsx
src/components/mypage/BookMarkedMate.tsx
src/components/mypage/WrittenMate.tsx
src/components/signUp/EmailAndPw.tsx
src/pages/ExhibitionList.tsx
src/pages/Login.tsx
src/pages/MateList.tsx
src/types/exhbList.d.ts

1. NoList 컴포넌트에 프롭스 추가했습니다. notice:string을 넘겨줍니다. 기존에 사용되던 NoList 컴포넌트들은 기존 문구로 다 넘겨주었습니다.
2. 로그인/회원가입 시 아이디 -> 이메일로 수정했습니다. 아이디/비밀번호 찾기 기능은 아직 없기 때문에 클릭 시 alert창이 뜨도록 수정했습니다.
3. 전시글 목록페이지의 필터가 SelectBox로 적용되지 않은 것을 발견해 적용했습니다. 
4. api연결이 되지 않고 목데이터로 연결되어있던 부분들 api로 연결했습니다
(전시글 목록 조회에서 전체전시 제외하고 기획전시, 영상전시 등은 현재 필터링이 제대로 되지 않고 데이터가 들어와서 그 부분 확인요청드린 상태입니다. ➡️ api 수정완료해주셔서 기능 비활성화 풀었습니다)
5. 전시글 목록 페이지 전시타입 필터 적용막아놨습니다. 백엔드 수정이 필요할 것 같은데 당장 불가능 할 것 같아서 막아달라고 요청이 들어왔습니다. 리팩토링 끝나고 나면 다시 적용할 예정입니다
6. 동규님 머지과정에서 MainArticle파일에서 에러를 발견해 수정했습니다.
따로 기능별로 브랜치를 분리하지 않고 feature/refactor-yesun 브랜치에서 전체적인 수정사항을 수정했습니다.
머지되면 브랜치는 삭제하겠습니다.

Refactor: 배포 전 점검(목데이터 말고 api로 연결, css 깨짐 수정, NoList컴포넌트 props추가)

---

src/components/exhibitionList/Filters.tsx
src/pages/ExhibitionList.tsx
src/types/exhbList.d.ts

기획분들과 상의하여 전시회 목록에서 필터 적용 버튼을 삭제하고,
필터를 선택하면 바로 목록을 불러들이는 로직으로 변경했습니다.
메이트 모집글도 필터 적용버튼 없애기로 했으니 곧 작업해서 pr하겠습니다

Fix: 전시회 목록 필터적용 버튼 삭제 #216

---

src/components/atom/Button.tsx

공통 버튼 컴포넌트 누락된 디자인 추가했습니다!
호버와 포커스 시 배경색이 다른 게 있는데 똑같게 되어있어서 그 부분도 수정했습니다
1. 탭키로 포커스 했을 때 디자인 누락되어있어 추가
2. focus (선택되었을 때, 피그마 상에선 active) 배경색 알맞게 수정
3. buttonsize 변수명 컨벤션에 맞게 수정
브랜치는 머지후 삭제예정입니다

Design: Button 컴포넌트 focus, active 시 빠진 디자인 추가

---

src/components/atom/Button.tsx
src/components/exhibitionList/ExhbCardList.tsx
src/components/exhibitionList/Filters.tsx
src/pages/ExhibitionList.tsx

1. 전시회 목록 페이지 카드리스트와 필터컴포넌트의 max-width가 설정되어있지 않아서 추가
2. 전시 상태 필터를 공통 버튼 컴포넌트로 변경

Design: 전시회 목록페이지 max-width추가, 공통 버튼 컴포넌트로 변경

---

src/App.tsx
src/components/ScrollTop.tsx
src/pages/Exhibition.tsx

전시회 목록에서 전시회 카드를 클릭하여 상세페이지에 들어가면 이전 페이지의 스크롤이 유지가 되어서
스크롤을 최상단으로 끌어올리는 컴포넌트를 추가했습니다.
전시회 상세페이지 뿐만 아니라 메인페이지에서 전시회 자세히 보기를 클릭해도 스크롤이 맨 위로 안올라가서,
아예 pathname이 바뀔때마다 스크롤을 위로 끌어올리도록 컴포넌트를 만들었습니다.
파일 위치는 src - component - ScrollTop.tsx 입니다
+) 처음엔 전시회 상세페이지에 useEffect로 렌더링될 때 맨 위로 끌어올리는 코드로 추가했다가 ScrollTop컴포넌트 추가한거라,
작업하면서 useState가 아래쪽에 따로 떨어져있는 코드 발견하고 위쪽으로 올렸습니다.

Fix: 전시회 상세페이지에 들어가면 최상단으로 스크롤 올라오도록 수정

---

src/apis/blogReviewApis.tsx
src/apis/exhibition.tsx
src/components/blogreview/container/BlogReviewDetailContainer.tsx
src/components/blogreview/presentation/BlogReviewDetailPresentation.tsx
src/components/mate/ExhbCard.tsx
src/pages/BlogReview.tsx
src/pages/BlogReviewDetail.tsx

1. 버튼들 기능 연결, 디자인 수정했습니다.
-1) 목록 - 클릭하면 전시리뷰 목록으로 이동
-2) 이전글, 다음글 - 클릭하면 일단 '준비 중인 기능입니다.' alert실행
-3) 삭제 - 기존에는 삭제버튼 클릭하면 삭제 후 바로 메인페이지로 이동하게 구현되어있었는데, alert으로 삭제됨 알려주고 전시리뷰 목록페이지로 이동하도록 수정 
-4) 유익해요 - onClick함수 연결, boolean 값에 따라 디자인 변경되도록 구현함.
-5) 북마크 - onClick함수 연결, boolean 값에 따라 디자인, 문구(저장됨/저장하기) 변경되도록 구현함.
-5-1) ‼️ 4, 5번 항목은 api 연결은 안해두어서 그 부분은 동규님이 하셔야합니다.
-6) 모든 버튼들에 테두리가 없어서 추가, 버튼사이 간격도 추가
2. 블로그리뷰 상세페이지의 전시회 정보 카드를 메이트글 상세페이지의 전시회 정보 카드를 재사용하는 것으로 교체.
- 기존에는 전시회 상세페이지의 카드를 그대로 가져오셨습니다. 근데 크기나 디자인(배경색, 썸네일크기, 좋아요나 공유버튼 없는 것)이 피그마와 달라서 찾아보니 메이트모집글의 전시회카드와 디자인이 동일한 것을 확인했고, 교체했습니다.
-> 2/7 기획/디자인 회의페이지를 보니 이것도 변경필요하더라구요 근데 일단은 급한건 아니니 요걸로 머지해두면 좋을 것 같아요
3. 블로그 리뷰 상세페이지(+ 자식컴포넌트들)의 넓이가 잘못 설정되어있어 변경.
4. 페이지 시작번호 1로 수정
- ‼️ 이 부분은 변경될 수 있습니다. 작업하다가 갑자기 데이터가 안불러와져서 이유를 찾다보니 페이지를 1로 설정하면 …

Fix: 블로그리뷰 상세페이지 버튼들 연결, css 수정

---

src/components/exhibitionList/ExhbCardList.tsx
src/components/exhibitionList/Filters.tsx
src/pages/ExhibitionList.tsx

1. 전시회 목록 필터들과 카드리스트가 화면 넓이만큼 꽉차보이는 부분 수정
2. 피그마에 화면 넓이 별 padding 추가해주셔서 반영
exbhCardList는 마이페이지에도 사용되는 컴포넌트지만 레이아웃 깨지는 부분 없는 것 확인했습니다

Design: 전시회목록 페이지 레이아웃 수정, padding 피그마 추가된 부분 반영

---

src/pages/MateWrite.tsx

1. 취소하기 버튼 클릭 시 모달 뒤로 어두운 뒷배경이 안나오는 부분 수정-> 모달컴포넌트 안에 집어넣지 않아서 그런거라 모달컴포넌트를 활용해 수정
2. 취소하기 버튼 클릭 시 나오는 문구 협의된 대로 수정
3. 본문 내용 입력창 위 타이틀 본문 내용으로 수정

Fix: 메이트 작성/수정 페이지 취소버튼 시 모달 수정, 디자인 수정

---

src/components/signUp/AdminOnly.tsx
src/components/signUp/CommonOnly.tsx
src/components/signUp/EmailAndPw.tsx

일반/관리자 회원가입 시 인풋창에 값을 입력했다가 빈칸으로 삭제해도 오류메세지가 떠서, 빈칸이면 오류가 뜨지 않고 원상태가 되도록 수정했습니다.

Fix: 회원가입 시 빈값이면 유효성검사하지 않도록 수정

---

src/pages/MateWrite.tsx

1. 메이트글을 작성하고 수정페이지에 들어가면 선택했던 전시회의 정보가 나오지 않는 버그 수정했습니다.
2. 1번 사항 수정과정에서 액세스토큰만료된 상태로 수정버튼을 클릭했는데 구현했던 에러로직이 바로 실행되지 않고 저번 로그아웃클릭시처럼 한번 더 클릭해야 실행되는 버그를 발견하고, try catch문을 이용해 수정했습니다.
이제 액세스토큰이 만료된 상태로 수정버튼을 클릭하면 바로 리프레시토큰 인증이 실행되고 그 인증이 성공되면 사용자 모르게 다시 수정요청이 가서 사용자입장에서 불편한 부분이 없게 됩니다
3. 메이트글 작성/수정 시 api요청에 실패 했을 때 단순히 mate-list로 navigate하는게 아니라 navigate(-1)을 해서 이전 페이지로 돌아가도록하고, 뒤로가기 버튼을 클릭해도 작성/수정페이지로 돌아가지 못하도록 했습니다.

Fix: 메이트글 수정시 기존 선택된 전시회가 나오지 않는 버그, 액세스토큰만료 응답 받아도 로직실행이 안되는 버그 수정

---

src/components/mate/MateListFilter.tsx
src/pages/MateWrite.tsx

백엔드분들과 협의해 관리자는 메이트글 작성/수정을 할 수 없게 수정했습니다.
1. 일반 사용자(로그인 여부 관계없이)에게만 메이트글 작성/수정 버튼을 표시
2. url로 작성/수정 페이지를 접속하면 리다이렉트

Fix: 관리자는 메이트글 작성/수정  할 수 없도록 버튼 숨김, 작성/수정 페이지 접속 시 리다이렉트

---

src/components/exhibitionList/ExhbCardList.tsx
src/components/exhibitionList/Filters.tsx
src/pages/ExhibitionList.tsx

1. 전시회 카드 가로세로 비율 축소 요청이 있어서 수정했습니다
2. 피그마를 다시 보니 '전시회'라는 타이틀과 nav바 사이의 여백이 달라 수정했습니다(이밖에 자잘한 여백도 변경이 있어 수정됨)
3. 전시 목록 상단 우측 검색창 
- 디자인적 수정사항은 검색아이콘이 조금 오른쪽으로 이동된 것 빼곤 없음
- 클릭/엔터 시 준비중입니다 알림창 추가
- 일반 css코드를 스타일드 컴포넌트로 수정
4. 사용하지 않는 css 클래스 코드 삭제(전에 지워야했는데 발견 못했던 부분)

전시회 목록 피그마 수정사항 반영, 전시목록 검색창 준비 중입니다 알림창 추가, css 리팩토링

---

src/App.tsx
src/components/blogReviewList/ReviewCard.tsx
src/components/blogReviewList/ReviewCardList.tsx
src/components/blogreview/container/BlogReviewReadContainer.tsx
src/components/blogreview/container/ReviewCardList.tsx
src/components/blogreview/presentation/BlogReviewCard.tsx
src/components/mypage/WrittenBlogReview.tsx
src/pages/BlogReviewList.tsx

1. 디자인 수정
-1) 리뷰 카드 비율 수정
-2) 이미지 아래쪽 border-radius:0으로 수정
-3) 전시 리뷰 제목이 nav바와 붙어있어서 여백 부여
-4) 작성자가 이미지를 첨부하지 않은 경우 로고이미지 표시(임시)
-5) 카드 호버 시 테두리, 그림자, 글자색 변경 반영
2. 코드 구조 변경
-1) 블로그리뷰 상세/마이페이지 에 쓰이는 컴포넌트들과 블로그리뷰 목록페이지에 쓰이는 컴포넌트들이 한 폴더에 섞여있어 blogReviewList라는 파일을 생성해 전시리뷰목록페이지에서 사용하는 컴포넌트들은 위치 이동, 파일명 알아보기 쉽게 수정
-2) 기존 BlogReview -> BlogReviewList로 컴포넌트명만 봐도 전시리뷰 목록 페이지인것을 알도록 파일명 수정
-3) App.tsx에 import 순서가 맞지 않아 수정
css 코드 좀 더 간결하게 할 수 있을 것 같은데 저도 시간이 많이 없어서 일단 요구사항대로 구현했습니다.
동규님께서 블로그리뷰 카드의 넓이를 고정하셔서 화면넓이가 줄어드는 대로 비율이 줄어들지 않습니다.
이 부분은 나중에 전시회 목록 페이지처럼 수정 들어가면 좋을 것 같네요

Fix: 전시 리뷰 목록 레이아웃과 이미지 없으면 엑박뜨던 부분 수정

---

src/components/mate/CommentList.tsx
src/components/mate/ExhbCard.tsx
src/components/mate/MateTop.tsx
src/pages/Mate.tsx

1. 썸네일 넓이 증가
2. 썸네일 우측 테두리 직선으로 변경
3. 상단 전시회 부분 배경색 추가
4. 전시회카드 부분 '전시유형' 추가 -> 백엔드에서 데이터 추가해줘야 해서 아직 데이터랑 연결은 안됨.
5. 이전글, 다음글 버튼 추가 -> 기능은 막아둠(alert)
상세페이지 하단은 아직 변경이 더 필요한데 블로그리뷰 상세페이지에도 이 카드 컴포넌트를 사용해야해서 먼저 pr합니다

Design: 전시회 상세페이지 상단 전시회 카드부분 디자인 수정

---

src/components/Calendar.tsx
src/pages/BlogReviewModify.tsx
src/pages/BlogReviewWrite.tsx
src/pages/Mate.tsx
src/pages/MateWrite.tsx

‼️블로그리뷰나 메이트글 수정 페이지에 접속시 선택한 날짜가 아닌 당일날짜가 보이는 오류를 수정했습니다.
1. 캘린더 컴포넌트는 selectedDate라는 props를 받게됩니다. 부모 컴포넌트의 selectedDate가 변경되면 캘린더 컴포넌트의 날짜, 선택날짜도 변경되게 됩니다.
2. 수정하며 역할에 대한 의미를 확실하게 알 수 없어서 헷갈렸던 변수/함수명을 수정했습니다.
- 캘린더에 표시되는 달을 나타내는 변수 : currentMonth -> showedMonth
- 사용자가 선택한 날짜의 번호를 나타내는 변수 : selectedNumber -> selectedDayNumber
- 달력의 오른쪽, 왼쪽 화살표 클릭 함수 : prevMonth/nextMonth -> clickArrowLeft, clickArrowRight
- 달력 날짜 클릭함수 : onDateSelect -> clickCalendarDay
3. 날짜가 아닌 날짜 사이사이를 클릭해도 날짜클릭함수가 발동하게 되어서 달력 전체가 아닌 날짜 요소에만 클릭이벤트를 주도록 수정했습니다
4. 오른쪽/왼쪽 화살표 버튼에 hover해도 마우스가 바뀌지 않아 커서바뀌도록 수정했습니다.
5. 달력컴포넌트의 수정사항을 반영해 메이트 모집글 작성/수정 컴포넌트를 수정했습니다
‼️ 기존 달력 컴포넌트를 사용한 컴포넌트들에는 일단 현재 날짜를 부여했습니다. 블로그리뷰 수정페이지에서 로직에 맞게 수정하셔야합니다.

Fix: Calendar 컴포넌트 기존 선택된 날짜 보이지 않던 버그 수정, 메이트 모집글 작성/수정페이지 달력 변경사항 반영

---

src/components/onelineReview/presentation/MypageOnelineCard.tsx
src/components/onelineReview/presentation/OnelineCard.tsx

프로필이미지 border-radius 수정했습니다
src/components/onelineReview/presentation/OnelineCard.tsx 만 확인하시면 됩니다.

Fix: 블로그리뷰 상세페이지 프로필 이미지 왜곡 수정

---

src/components/blogreview/container/BlogReviewDetailContainer.tsx
src/components/onelineReview/presentation/MypageOnelineCard.tsx
src/pages/BlogReviewDetail.tsx
src/types/blogReview.d.ts

전시 타입 표시 추가
이제 홈페이지에서 전시리뷰로 넘어가도 로그인하지 않은 채 전시회 정보카드를 확인할 수 있습니다

Fix: 블로그 상세리뷰 페이지 전시 타입 표시 수정

---

src/components/atom/SearchInput.tsx
src/components/blogReviewList/ReviewCard.tsx
src/components/exhibitionList/Filters.tsx
src/components/mate/MateListFilter.tsx
src/pages/BlogReviewList.tsx

1. 제가 기존 작성했던 검색 input을 컴포넌트화 한 후 atom폴더에 넣었습니다.
- Searchbar라는 컴포넌트가 있긴 했는데 적용된 부분을 보니 아직 페이지 레이아웃이 미완이라 혹시 깨질까봐 제가 새로 만들었습니다.
2. 전시리뷰 목록페이지에 검색input이 피그마와 다른 형태로 들어가있어 컴포넌트를 이용해 수정했습니다
- 돋보기 아이콘이 없고 글자수 표시가 있었음
- 기능은 막아뒀음
3. 전시회목록/메이트글 목록 페이지의 검색창을 아톰 컴포넌트를 활용해서 수정했습니다.(디자인은 기존과 같음)

Design: 검색input 컴포넌트화 후 전시리뷰 목록페이지에 적용

---

src/components/mate/MateTop.tsx
src/styles/theme.tsx

- 피그마 페이지별 타이틀이나 전시카드 뒤의 Bg컬러가 모두 같다는 것을 진아님께 확인받았습니다.
- 피그마상 rgba(149, 141, 165, 0.05); 컬러. => #958DA5에 투명도 5%인.
- hex코드로 변경후 반영했습니다
- 바로는 아니더라도 추후 이 속성이용해서 변경해주시면 좋을 것 같아요!
- 확인을 위해 메이트글 상세페이지에 적용해보았습니다. 잘 작동합니다!

Setting: 공통적으로 사용되는 Bg 컬러 추가

---

src/components/main/MainArticle.tsx
src/components/main/NewCarousel.tsx

1. 메인페이지 캐러셀 반응형으로 수정. 화면의 넓이에 따라 비율대로 높이도 줄어듭니다. 하지만 400픽셀 미만으로는 줄어들지 않습니다
- 글자도 반응형으로 줄어듧니다. 높이가 최소높이인 400픽셀이 될 때는 그 이하로 화면이 줄어도 글자크기가 유지됩니다
- 페이지수를 나타내는 점들도 가운데를 유지합니다. 기존에는 화면이 작아질때 점들이 약간 오른쪽으로 치우치는 경향이 있었는데, 라이브러리 내의 클래스를 찾아 속성을 변경해주어 가운데를 유지하도록 했습니다.
2. 메인카드 3개의 크기, 글자크기도 반응형으로 수정.
- 기존에는 화면이 줄어들어 글자가 밑으로 내려갈 때 한글자씩 내려가서 가독성이 떨어졌었습니다 -> 웹접근성 문제
- 다양한 / ~~~ / 찾아보세요 설명을 단어단위로 span으로 끊어서 단어단위로 내려가도록 했습니다.
- 자세히 보기도 마찬가지로 화면이 줄어들때 자세히 보/기 로 끊어지던 부분을 자세히 /보기 로 끊어지도록 했습니다
3. LinkContainer -> SeeMore 자세히보기 링크기능이 사라지고 메인카드 전체에 들어가서, 스타일드 컴포넌트명을 변경했습니다
4. 메인카드들에 호버하면 그림자도 생겨야하는데 없어서 추가했습니다

Design: 메인페이지 반응형으로 수정

---

src/components/Footer.tsx

1. JopGroup의 지정된 넓이를 없애 화면이 줄어들면 글자들 사이의 여백이 줄어들도록 함.
- 너무 줄어들면 글자가 깨져서 최소 넓이는 지정함. 최소넓이들보다 화면 줄어들면 flex-wrap:wrap 속성으로 아래로 내려감
2. 푸터 위아래 여백을 화면이 줄어들면 그에 맞는 비율로 줄어들게 함. 기본은 원래여백. 줄어들때만 바뀜
3. 화면넓이에 따라 글자크기 반응형으로 줄어듦
4. > 문의하기 < 를 누르면 구글폼으로 이동하는데, 눈에 안띄어서 진한 글씨로 바꿔봄 -> 반영된 후 팀원들 피드백 필요할 듯
이제 화면 줄어들어도 안깨질 거에요!

Design: footer 반응형으로 수정

---

src/components/atom/SimpleInput.tsx
src/components/onelineReview/container/OnelineModifyContainer.tsx
src/components/onelineReview/container/OnelineWriteContainer.tsx

- 한줄리뷰 60자 이상 작성시 알림과 함께 제출하지 못하도록 수정
- 인풋창의 레이아웃 문제는 일단 px => %의 상대값으로 전환했습니다.
- 액세스 토큰 처리 추가 
- 이 부분 현재 구조로는 에러처리의 주도권을 react와 react-query가 공유하고 있어 문제가 발생할 수 있습니다. 차후 컴포넌트단에서 토큰을 취급하지 않아도 되도록 구조개선 예정입니다.

Feat: 한줄리뷰 작성, 수정 토큰처리 및 유효성검사

---

src/components/mate/CommentList.tsx
src/pages/Mate.tsx

메이트글 상세페이지를 모바일에서 봤을 때 보라색 박스 부분의 레이아웃이 깨져보이는 것을 수정했습니다.
피그마에 반응형으로 기재되어있는 디자인은 아니지만 모바일에서 깨지지 않도록 임시로 수정했습니다.
머지 후 전체 팀원에게 고지하고, 변경할 부분이 생기면 그때 다시 변경할게요!
지금은 레이아웃이 깨지지 않게 하기 위한 것을 우선으로 잡았습니다.
작업내용
1. 박스세개를 감싸는 컨테이너에 flex-wrap: wrap을 부여해 크기가 넘칠 시 박스가 아래로 내려가도록 했습니다.
2. 미디어 쿼리로 넓이에 따라 부여하던 패딩값을 더 자연스럽게 변경했습니다
(화면넓이에 따라 확확바뀌는게 아니라 연결되며 바뀌도록 보이게 함)
3. 메이트글 상세페이지의 댓글 영역의 패딩도 본문 영역의 패딩과 동일하게 변경되도록 했습니다
➡️ 변경 전
➡️ 변경 후

Design: 메이트글 상세페이지 보라색박스 영역 반응형 추가

---

src/components/mate/CommentList.tsx
src/components/mate/ExhbCard.tsx
src/components/mate/MateTop.tsx
src/pages/Mate.tsx

메이트글 상세페이지의 전시회 카드부분이 모바일크기에서는 레이아웃이 많이 깨져 수정했습니다.(블로그리뷰 상세페이지도 동일)
이 부분도 임시로 깨지지않게만 해둔거고, 피드백 들어오면 또 수정될 수 있습니다
1. 넓이에 따라 글자크기, line-height, 제목과 장소, 일정, 상태 라벨사이 간격 변경(일정 크기 이하로 줄어들진 않음)
2. 370이하로 내려가면 또 깨지기 때문에 그 이하일 때는 이미지가 왼쪽이 아닌 위쪽으로 배치되도록 수정
<div style="flex">
🔥 변경 전
🔥 변경 후
🔥 변경 후(370픽셀 이하)
</div >

Design: 메이트글 상세페이지, 블로그리뷰 상세페이지 전시회 카드영역 반응형 추가

---

src/components/mate/ExhbCard.tsx

둘러보다가 setTimeout을 발견해서 useEffect 콜백을 추가했습니다.  
리액트의 경우 useEffect내부에 setTimeout, setInterval을 설정해두면 컴포넌트가 언마운트 되더라도 타이머는 그대로 남아있습니다. 별다른 부작용은 없어보이지만 일단 클린업 했습니다. 
자세히 설명하자면 setInterval로 카운터를 만들어보면 알기 쉬운데 1초마다 하나씩 증가하는 카운터를 만들었을 때 클린업하지 않으면 언마운트 -> 리마운트되었을 때 1초에 2씩 증가하게 됩니다. strict모드에서 컴포넌트가 두 번씩 마운팅 되는 것도 이런 눈치채기 어려운 버그를 탐지하기 위한 로직입니다.

Refactor: 전시회 카드 컴포넌트에 useEffect 클린업 콜백 추가

---

src/apis/getExhbList.tsx
src/components/ExhibitionChoice.tsx
src/components/exhibitionList/Filters.tsx
src/pages/ExhibitionList.tsx
src/types/exhbList.d.ts

1. 전시회 목록 조회하는 api가 두가지로 나눠졌었는데 하나로 통일됨
- 타입이 전체전시인지, 그외 영상전시, 그림전시 등인지에 따라 나뉘었는데 하나로 통일됨.
2. sort라는 파라미터가 api에 추가됨. 정렬이 최신순으로만 되었었는데 조회수순도 추가됨(인기순이었는데 변경됨)
- 블로그리뷰/메이트글 작성에 사용되는 전시회 선택모달에도 전시회목록 조회 api 사용되어서 에러없게 수정함.
현재 수정은 다 완료되었는데 백엔드에 요청을 보내도 조회수순 정렬이 안돼서 그 부분은 다시 말씀드릴 예정입니다.

Fix: 전시회 목록 정렬 필터 인기순-> 조회수순으로 변경, 기능 추가 + api 수정됨

---

src/apis/mate.tsx
src/pages/MateList.tsx

1. 메이트글 목록 조회 api에서 '전체' 필터이면 값을 안넣는 구조였는데, 전체도 값을 넣는 구조로 변경되어 반영했습니다
2. 메이트글 목록 조회 실패 시 메인페이지로 리다이렉트 기능 추가했습니다
현재 백엔드 코드만 수정된 상태로 버그 발생중이니 빠른 확인 부탁드립니다.

Fix: 메이트글 목록 조회 api 수정, 메이트글 목록 조회 실패시 메인페이지로 리다이렉트 기능 추가

---

src/components/blogReviewList/ReviewCardList.tsx
src/pages/BlogReview.tsx

NoList 컴포넌트가 자식컴포넌트 넓이인 380px로 고정이 되어나와서 ReviewCardListContainer 컴포넌트 바깥으로 위치를 이동했습니다

Design: 전시리뷰 목록 없을 시 NoList 컴포넌트 레이아웃 깨짐 수정

---

src/apis/exhibition.tsx
src/components/atom/BookMark.tsx
src/components/exhibition/MainCard.tsx

1. 북마크를 클릭했을 때 발생하는 두가지의 함수가 각자 다른 파일에서 관리되고 있어 유지보수를 위해 북마크 파일에서 관리하도록 위치를 이동하고, 함수를 합쳤습니다. 
2. 북마크 여부를 부모 컴포넌트에서 북마크 컴포넌트로 넘겨주는데, 가독성과 유지보수를 위해 변수명을 marked-> bookmarked로 통일했습니다.
3. 기존 로직은 클릭했을 경우 토큰이 있든 없든/ 통신에 성공하든 실패하든 무조건 색상이 변경되는데 토큰이 없으면 로그인 알림이 뜨고 return을 하도록 하여 색상변경이 이루어지지 않도록 했습니다. 마찬가지로 통신에 실패해도 색상변경이 되지 않도록 성공시에만 setIsChecked((prev) => !prev);를 넣었습니다.
4. 동규님이 변경하셨는데 아직 반영이 안된 전시글 북마크 api 여기서도 변경했습니다. 테스트를 위해 변경했는데 아직 동규님 pr이 머지가 안되어서 제가 먼저 될 수도 있어서 이 pr에도 포함시켰습니다.

Fix: 전시회상세페이지 북마크 실패해도 아이콘 변경되는 오류 수정

---

src/components/atom/Searchbar.tsx
src/components/reviewCommon/ReviewSearchBar.tsx

- exhibition/${number}페이지에서 검색창에 보이는 플레이스 홀더 삭제
- 클릭 시 아직 지원하지 않는 기능 표시
- 백엔드에서 기능은 만들어주셨고 제가 구현하는데는 아직 시간이 약간 걸릴 것 같아 표시만 변경해뒀습니다..

Fix: exhibition 개별 페이지 searchBar 컴포넌트 수정

---

src/pages/ExhibitionList.tsx

- 전시회 목록 조회에 실패했을 시 그대로 전시회 목록 페이지에 위치함으로서 사용자에게 잘못된 정보를 보여주는 것보단 메인페이지로 이동하는 게 좋을 것 같아서 추가했습니다.

Fix: 전시회 목록 조회 요청 실패 시 메인페이지로 리다이렉트

---

src/pages/BlogReviewModify.tsx
src/pages/BlogReviewWrite.tsx

1. 전시리뷰 작성 컴포넌트(BlogReviewWrite)
- selectedDate 상태 초기값을 "" => format(new Date(), "yyyy-mm-dd")로 수정
- 캘린더 컴포넌트에 전달해주는 값을 new Date() => new Date(selectedDate)로 수정
- 날짜를 클릭하면 바로 selectedDate가 업데이트 되기 때문에 이제 한번만 클릭해도 바로 날짜 정상반영됩니다!
- 작성 후 블로그리뷰 상세페이지에서 선택된 날짜 정상 표시 되는 부분 확인했습니다.
- ‼️다만 수정페이지 들어가면 아직 오늘 날짜로 보여서 동규님이 수정해주셔야 합니다!
2. 전시리뷰 수정 컴포넌트(BlogReviewModify)
- ‼️현재 어떤 방식으로 작성 시 선택된 날짜를 받아오고 있는지 모르겠어서 일단 주석 추가해두었습니다. 동규님께서 확인하시고 수정해주시면 될 것 같아요
- ‼️전시 리뷰 수정 시 기존에 작성했던 제목이 안보이는 오류가 추가로 있습니다. 그것도 수정하셔야 할 것 같네요
3. 사용하지 않는 import 삭제
동규님 승인 후 머지하겠습니당

Fix: 전시리뷰 작성페이지 날짜 두번 클릭해야 선택되는 오류 수정

---

public/index.html

전시회 포스터 이미지가 무분별하게 저장되는 것을 막기 위해 body 태그에 우클릭 방지 속성을 추가해주었습니다.
처음에는 이미지 하나하나에 속성을 적용하려고 했으나 
body 태그가 아닌 다른 태그에서는 동작을 하지 않아 body 태그에 속성을 추가했습니다.

Feat: 이미지 우클릭 방지 기능 추가

---

src/apis/blogReviewApis.tsx
src/components/blogReviewList/ReviewCard.tsx
src/components/blogreview/container/BlogReviewReadContainer.tsx
src/components/onelineReview/presentation/MypageOnelineCard.tsx

1. 로그인 안 한 상태에서 블로그 리뷰 클릭 시 상세페이지 정보가 표시되도록 수정
2. 전시회 상세페이지의 블로그 리뷰 목록에서 제목과 닉네임 왼쪽 정렬
3. 블로그 리뷰 글의 제목이 너무 긴 경우 하단의 정보들이 다같이... 표시로 전환
4. '마이페이지-작성글 조회-한줄리뷰' 에서 별점의 별을 가로정렬

Fix: 비 로그인시 블로그 리뷰 상세표시와 css 정렬수정

---

src/apis/exhbList.tsx
src/components/ExhibitionChoice.tsx
src/components/exhibitionList/Filters.tsx
src/pages/ExhibitionList.tsx

1. 전시글 검색기능을 구현하며 기존 전시글 목록조회와 전시글 목록 검색 조회가 나눠져있던 게 합쳐져서 title파라미터를 추가했습니다.
2. 백엔드의 요청으로 sort "최신순"이면 ""으로, type "전체 전시"면 ""로 파라미터 값을 수정했습니다.
3. 전시글 목록 api 파일명 다른 api 파일명들과 통일감 있게 수정했습니다.
4. 전시글 목록 검색창 placeholder 전체 다수결 투표한 결과 반영했습니다.

Fix: 전시글목록 api 수정사항 반영(전시회 제목 검색 title 파라미터 추가, sort/type파라미터 기본값 ""으로 수정"

---

src/apis/exhbList.tsx
src/components/ExhibitionChoice.tsx
src/pages/ExhibitionList.tsx
src/pages/MateList.tsx
src/types/mateList.d.ts

- 전시회 목록, 메이트글 목록 조회 api를 변경할 때 총 페이지 수 부분 응답형식도 변경됐는데 그 부분을 제가 반영하지 않고 머지를 해서 오류가 생겼었습니다. 수정완료했습니다~

HOTFIX: 전시회 목록, 메이트글 목록 조회 api 응답형식 변경(totalPage 부분) 미반영으로 인한 오류 수정

---

src/apis/mate.tsx

- 모집상태 '전체'일 경우 공백으로 보냄
- 검색키워드 title 파라미터 추가(아직 검색기능이 추가되진 않아서 공백으로 보내고 있습니다. 기능은 정상작동합니다!)

Fix: 메이트글 목록조회api 수정사항 반영

---

src/apis/exhbList.tsx
src/components/ExhibitionChoice.tsx
src/components/exhibitionList/Filters.tsx
src/pages/ExhibitionList.tsx

- 전시회 목록 검색창에 제목을 기준으로 검색이 가능해졌습니다.
- ExhibitionChoice 컴포넌트(블로그 작성과 메이트글 작성 시 사용되는)에는 검색창이 없기 때문에 api 요청시 default로 ""을 넘겨주도록 했습니다. 정상작동확인했습니다
+++++))) 원래 검색을 실시하면 검색창 옆에 보라색 초기화 버튼을 누르는 방향으로 구현하기로 했는데,
조금 작업이 더 걸릴 것 같아서 일단 검색기능만 추가했습니다. 현재는 새로고침을 해야만 초기화가 가능합니다

Feat: 전시회목록 전시제목으로 검색하는 기능 추가
